CREATE DATABASE private_school;

USE private_school;

CREATE TABLE courses (
    course_id INT NOT NULL AUTO_INCREMENT,
    course_title VARCHAR(45) NOT NULL,
    course_stream VARCHAR(45),
    course_type VARCHAR(45),
    start_date DATE,
    end_date DATE,
    PRIMARY KEY (course_id)
);


CREATE TABLE students (
    student_id INT NOT NULL AUTO_INCREMENT,
    first_name VARCHAR(45) NOT NULL,
    last_name VARCHAR(45) NOT NULL,
    date_of_birth DATE,
    tuition_fees FLOAT,
    PRIMARY KEY (student_id)
);

CREATE TABLE assignments (
    assignment_id INT NOT NULL AUTO_INCREMENT,
    assignment_title VARCHAR(45) NOT NULL,
    assignment_description VARCHAR(45),
    sub_date_time DATETIME,
    oral_mark INT,
    total_mark INT,
    course_id INT,
    PRIMARY KEY (assignment_id),
    FOREIGN KEY (course_id)
        REFERENCES courses (course_id),
    UNIQUE (assignment_id , course_id)
);

CREATE TABLE trainers (
    trainer_id INT NOT NULL AUTO_INCREMENT,
    first_name VARCHAR(45) NOT NULL,
    last_name VARCHAR(45) NOT NULL,
    subject VARCHAR(45),
    PRIMARY KEY (trainer_id)
);

CREATE TABLE students_per_course (
    student_id INT NOT NULL,
    course_id INT NOT NULL,
    PRIMARY KEY (student_id , course_id),
    FOREIGN KEY (student_id)
        REFERENCES students (student_id),
    FOREIGN KEY (course_id)
        REFERENCES courses (course_id)
);

CREATE TABLE trainers_per_course (
    trainer_id INT NOT NULL,
    course_id INT NOT NULL,
    PRIMARY KEY (trainer_id , course_id),
    FOREIGN KEY (trainer_id)
        REFERENCES trainers (trainer_id),
    FOREIGN KEY (course_id)
        REFERENCES courses (course_id)
);

CREATE TABLE assignments_per_student (
    assignment_per_student_id INT NOT NULL AUTO_INCREMENT,
    assignment_id INT NOT NULL,
    student_id INT NOT NULL,
    student_sub_date_time DATETIME,
    student_oral_mark INT,
    student_total_mark INT,
    PRIMARY KEY (assignment_per_student_id),
    FOREIGN KEY (assignment_id) REFERENCES assignments (assignment_id),
    FOREIGN KEY (student_id) REFERENCES students (student_id),
    UNIQUE (assignment_id, student_id)
);

# POPULATE DATABASE 
USE PRIVATE_SCHOOL;
# Mock data insertion queries to Courses Table
INSERT INTO COURSES VALUES (NULL, 'CB9-Java-PT', 'Java', 'Part-time', '2019-10-07', '2020-04-22');
INSERT INTO COURSES VALUES (NULL, 'CB9-Java-PT-II', 'Java', 'Part-time', '2019-11-11', '2020-05-25');
INSERT INTO COURSES VALUES (NULL, 'CB9-Java-FT', 'Java', 'Full-time', '2019-10-07', '2020-02-25');
INSERT INTO COURSES VALUES (NULL, 'CB9-Csharp-PT', 'Csharp', 'Part-time', '2019-10-07', '2020-04-22');
INSERT INTO COURSES VALUES (NULL, 'CB9-Csharp-PT-II', 'Csharp', 'Part-time', '2019-11-18', '2020-06-01');
INSERT INTO COURSES VALUES (NULL, 'CB9-Csharp-FT', 'Csharp', 'Full-time', '2019-10-07', '2020-02-25');


# Mock data insertion queries to Assignments Table
INSERT INTO ASSIGNMENTS VALUES (NULL, 'Individual Project - Part A (JAVA-PT-II)', NULL, '2020-01-02 23:59:59', 20, 100, (SELECT COURSE_ID FROM COURSES WHERE COURSE_TITLE = 'CB9-Java-PT-II'));
INSERT INTO ASSIGNMENTS VALUES (NULL, 'Individual Project - Part A (JAVA-PT)', NULL, '2019-12-02 23:59:59', 20, 100, (SELECT COURSE_ID FROM COURSES WHERE COURSE_TITLE = 'CB9-Java-PT'));
INSERT INTO ASSIGNMENTS VALUES (NULL, 'Individual Project - Part B (JAVA-PT-II)', NULL, '2020-01-30 23:59:59', 20, 100, (SELECT COURSE_ID FROM COURSES WHERE COURSE_TITLE = 'CB9-Java-PT-II'));
INSERT INTO ASSIGNMENTS VALUES (NULL, 'Individual Project - Part B (JAVA-PT)', NULL, '2020-01-02 23:59:59', 20, 100, (SELECT COURSE_ID FROM COURSES WHERE COURSE_TITLE = 'CB9-Java-PT'));

INSERT INTO ASSIGNMENTS VALUES (NULL, 'Individual Project - Part A (C#-PT-II)', NULL, '2020-01-02 23:59:59', 20, 100, (SELECT COURSE_ID FROM COURSES WHERE COURSE_TITLE = 'CB9-Csharp-PT-II'));
INSERT INTO ASSIGNMENTS VALUES (NULL, 'Individual Project - Part A (C#-PT)', NULL, '2019-12-02 23:59:59', 20, 100, (SELECT COURSE_ID FROM COURSES WHERE COURSE_TITLE = 'CB9-Csharp-PT'));
INSERT INTO ASSIGNMENTS VALUES (NULL, 'Individual Project - Part B (C#-PT-II)', NULL, '2020-01-30 23:59:59', 20, 100, (SELECT COURSE_ID FROM COURSES WHERE COURSE_TITLE = 'CB9-Csharp-PT-II'));
INSERT INTO ASSIGNMENTS VALUES (NULL, 'Individual Project - Part B (C#-PT)', NULL, '2020-01-02 23:59:59', 20, 100, (SELECT COURSE_ID FROM COURSES WHERE COURSE_TITLE = 'CB9-Csharp-PT'));

INSERT INTO ASSIGNMENTS VALUES (NULL, 'Assignment 1 - HTML/JS (JAVA-PT-II)', NULL, '2020-02-14 23:59:59', 20, 100, (SELECT COURSE_ID FROM COURSES WHERE COURSE_TITLE = 'CB9-Java-PT-II'));
INSERT INTO ASSIGNMENTS VALUES (NULL, 'Assignment 1 - HTML/JS (JAVA-PT)', NULL, '2020-01-14 23:59:59', 20, 100, (SELECT COURSE_ID FROM COURSES WHERE COURSE_TITLE = 'CB9-Java-PT'));
INSERT INTO ASSIGNMENTS VALUES (NULL, 'Assignment 2 - MVC (JAVA-PT-II)', NULL, '2020-03-20 23:59:59', 20, 100, (SELECT COURSE_ID FROM COURSES WHERE COURSE_TITLE = 'CB9-Java-PT-II'));
INSERT INTO ASSIGNMENTS VALUES (NULL, 'Assignment 2 - MVC (JAVA-PT)', NULL, '2020-02-20 23:59:59', 20, 100, (SELECT COURSE_ID FROM COURSES WHERE COURSE_TITLE = 'CB9-Java-PT'));

INSERT INTO ASSIGNMENTS VALUES (NULL, 'Assignment 1 - HTML/JS (C#-PT-II)', NULL, '2020-02-14 23:59:59', 20, 100, (SELECT COURSE_ID FROM COURSES WHERE COURSE_TITLE = 'CB9-Csharp-PT-II'));
INSERT INTO ASSIGNMENTS VALUES (NULL, 'Assignment 1 - HTML/JS (C#-PT)', NULL, '2020-01-14 23:59:59', 20, 100, (SELECT COURSE_ID FROM COURSES WHERE COURSE_TITLE = 'CB9-Csharp-PT'));
INSERT INTO ASSIGNMENTS VALUES (NULL, 'Assignment 2 - .NET (C#-PT-II)', NULL, '2020-03-20 23:59:59', 20, 100, (SELECT COURSE_ID FROM COURSES WHERE COURSE_TITLE = 'CB9-Csharp-PT-II'));
INSERT INTO ASSIGNMENTS VALUES (NULL, 'Assignment 2 - .NET (C#-PT)', NULL, '2020-02-20 23:59:59', 20, 100, (SELECT COURSE_ID FROM COURSES WHERE COURSE_TITLE = 'CB9-Csharp-PT'));


# Mock data insertion queries for Students Table
INSERT INTO STUDENTS VALUES (NULL, 'Nikos', 'Nikolaou', '1990-01-01', 2500);
INSERT INTO STUDENTS VALUES (NULL, 'Giorgos', 'Alexandrou', '1988-03-11', 2500);
INSERT INTO STUDENTS VALUES (NULL, 'Kostas', 'Aggelopoulos', '1994-06-21', 2500);
INSERT INTO STUDENTS VALUES (NULL, 'Niki', 'Apostolopoulou', '1989-07-09', 2500);
INSERT INTO STUDENTS VALUES (NULL, 'Erika', 'Petrou', '1990-11-09', 2500);
INSERT INTO STUDENTS VALUES (NULL, 'Anna', 'Psimouli', '1992-01-15', 2500);
INSERT INTO STUDENTS VALUES (NULL, 'Vasilis', 'Grigoriou', '1995-02-03', 2500);
INSERT INTO STUDENTS VALUES (NULL, 'Nikos', 'Papadopoulos', '1991-07-12', 2500);
INSERT INTO STUDENTS VALUES (NULL, 'Panagiotis', 'Vournas', '1985-05-12', 2500);


# Mock data insertion queries for Trainers Table
INSERT INTO TRAINERS VALUES (NULL, 'Giorgos', 'Mourgelas', 'Java');
INSERT INTO TRAINERS VALUES (NULL, 'Dimitris', 'Karalis', 'Csharp');
INSERT INTO TRAINERS VALUES (NULL, 'Eleni', 'Theodorou', 'HTML/CSS');
INSERT INTO TRAINERS VALUES (NULL, 'Thalia', 'Efthimiou', 'Javascript');
INSERT INTO TRAINERS VALUES (NULL, 'Kostas', 'Daskalakis', 'Java');
INSERT INTO TRAINERS VALUES (NULL, 'Manos', 'Giotis', 'Csharp');


# Mock data insertion queries for Students_Per_Course Table
INSERT INTO STUDENTS_PER_COURSE VALUES (1, (SELECT COURSE_ID FROM COURSES WHERE COURSE_TITLE = 'CB9-Java-PT'));
INSERT INTO STUDENTS_PER_COURSE VALUES (2, (SELECT COURSE_ID FROM COURSES WHERE COURSE_TITLE = 'CB9-Java-PT-II'));
INSERT INTO STUDENTS_PER_COURSE VALUES (3, (SELECT COURSE_ID FROM COURSES WHERE COURSE_TITLE = 'CB9-Java-PT'));
INSERT INTO STUDENTS_PER_COURSE VALUES (4, (SELECT COURSE_ID FROM COURSES WHERE COURSE_TITLE = 'CB9-Java-PT-II'));
INSERT INTO STUDENTS_PER_COURSE VALUES (5, (SELECT COURSE_ID FROM COURSES WHERE COURSE_TITLE = 'CB9-Csharp-PT'));
INSERT INTO STUDENTS_PER_COURSE VALUES (6, (SELECT COURSE_ID FROM COURSES WHERE COURSE_TITLE = 'CB9-Csharp-PT-II'));
INSERT INTO STUDENTS_PER_COURSE VALUES (7, (SELECT COURSE_ID FROM COURSES WHERE COURSE_TITLE = 'CB9-Csharp-PT'));
INSERT INTO STUDENTS_PER_COURSE VALUES (8, (SELECT COURSE_ID FROM COURSES WHERE COURSE_TITLE = 'CB9-Csharp-PT-II'));
INSERT INTO STUDENTS_PER_COURSE VALUES (9, (SELECT COURSE_ID FROM COURSES WHERE COURSE_TITLE = 'CB9-Java-FT'));
INSERT INTO STUDENTS_PER_COURSE VALUES (8, (SELECT COURSE_ID FROM COURSES WHERE COURSE_TITLE = 'CB9-Java-PT'));
INSERT INTO STUDENTS_PER_COURSE VALUES (6, (SELECT COURSE_ID FROM COURSES WHERE COURSE_TITLE = 'CB9-Java-PT-II'));
INSERT INTO STUDENTS_PER_COURSE VALUES (4, (SELECT COURSE_ID FROM COURSES WHERE COURSE_TITLE = 'CB9-Csharp-PT'));
INSERT INTO STUDENTS_PER_COURSE VALUES (2, (SELECT COURSE_ID FROM COURSES WHERE COURSE_TITLE = 'CB9-CSHARP-FT'));
INSERT INTO STUDENTS_PER_COURSE VALUES (1, (SELECT COURSE_ID FROM COURSES WHERE COURSE_TITLE = 'CB9-Csharp-PT'));

# Mock data queries for Traines_per_course Table
INSERT INTO TRAINERS_PER_COURSE VALUES (1, (SELECT COURSE_ID FROM COURSES WHERE COURSE_TITLE = 'CB9-JAVA-PT-II'));
INSERT INTO TRAINERS_PER_COURSE VALUES (1, (SELECT COURSE_ID FROM COURSES WHERE COURSE_TITLE = 'CB9-JAVA-FT'));
INSERT INTO TRAINERS_PER_COURSE VALUES (2, (SELECT COURSE_ID FROM COURSES WHERE COURSE_TITLE = 'CB9-CSHARP-PT-II'));
INSERT INTO TRAINERS_PER_COURSE VALUES (2, (SELECT COURSE_ID FROM COURSES WHERE COURSE_TITLE = 'CB9-CSHARP-FT'));
INSERT INTO TRAINERS_PER_COURSE VALUES (3, (SELECT COURSE_ID FROM COURSES WHERE COURSE_TITLE = 'CB9-CSHARP-FT'));
INSERT INTO TRAINERS_PER_COURSE VALUES (3, (SELECT COURSE_ID FROM COURSES WHERE COURSE_TITLE = 'CB9-JAVA-FT'));
INSERT INTO TRAINERS_PER_COURSE VALUES (3, (SELECT COURSE_ID FROM COURSES WHERE COURSE_TITLE = 'CB9-JAVA-PT'));
INSERT INTO TRAINERS_PER_COURSE VALUES (3, (SELECT COURSE_ID FROM COURSES WHERE COURSE_TITLE = 'CB9-CSHARP-PT-II'));
INSERT INTO TRAINERS_PER_COURSE VALUES (4, (SELECT COURSE_ID FROM COURSES WHERE COURSE_TITLE = 'CB9-CSHARP-PT'));
INSERT INTO TRAINERS_PER_COURSE VALUES (4, (SELECT COURSE_ID FROM COURSES WHERE COURSE_TITLE = 'CB9-JAVA-PT'));
INSERT INTO TRAINERS_PER_COURSE VALUES (4, (SELECT COURSE_ID FROM COURSES WHERE COURSE_TITLE = 'CB9-JAVA-FT'));
INSERT INTO TRAINERS_PER_COURSE VALUES (4, (SELECT COURSE_ID FROM COURSES WHERE COURSE_TITLE = 'CB9-CSHARP-PT-II'));
INSERT INTO TRAINERS_PER_COURSE VALUES (5, (SELECT COURSE_ID FROM COURSES WHERE COURSE_TITLE = 'CB9-JAVA-PT'));
INSERT INTO TRAINERS_PER_COURSE VALUES (5, (SELECT COURSE_ID FROM COURSES WHERE COURSE_TITLE = 'CB9-JAVA-FT'));
INSERT INTO TRAINERS_PER_COURSE VALUES (6, (SELECT COURSE_ID FROM COURSES WHERE COURSE_TITLE = 'CB9-CSHARP-PT'));
INSERT INTO TRAINERS_PER_COURSE VALUES (6, (SELECT COURSE_ID FROM COURSES WHERE COURSE_TITLE = 'CB9-CSHARP-PT-II'));


# Mock data queries for Assignments_per_student Table
INSERT INTO ASSIGNMENTS_PER_STUDENT VALUES (NULL, 2, 1, '2019-12-01 10:00:00', 20, 95);
INSERT INTO ASSIGNMENTS_PER_STUDENT VALUES (NULL, 4, 1, '2019-01-02 11:00:00',20, 100);
INSERT INTO ASSIGNMENTS_PER_STUDENT VALUES (NULL, 10, 1, NULL , NULL, NULL);
INSERT INTO ASSIGNMENTS_PER_STUDENT VALUES (NULL, 12, 1, NULL , NULL, NULL);

INSERT INTO ASSIGNMENTS_PER_STUDENT VALUES (NULL, 1, 2, '2019-01-02 23:50:00', 20, 98);
INSERT INTO ASSIGNMENTS_PER_STUDENT VALUES (NULL, 3, 2, '2019-01-02 11:00:00', 20, 96);
INSERT INTO ASSIGNMENTS_PER_STUDENT VALUES (NULL, 9, 2, NULL , NULL, NULL);
INSERT INTO ASSIGNMENTS_PER_STUDENT VALUES (NULL, 11, 2, NULL , NULL, NULL);

INSERT INTO ASSIGNMENTS_PER_STUDENT VALUES (NULL, 2, 3, '2019-12-01 10:00:00', 20, 95);
INSERT INTO ASSIGNMENTS_PER_STUDENT VALUES (NULL, 4, 3, '2019-01-02 11:00:00',20, 100);
INSERT INTO ASSIGNMENTS_PER_STUDENT VALUES (NULL, 10, 3, NULL , NULL, NULL);
INSERT INTO ASSIGNMENTS_PER_STUDENT VALUES (NULL, 12, 3, NULL , NULL, NULL);

INSERT INTO ASSIGNMENTS_PER_STUDENT VALUES (NULL, 1, 4, '2019-01-02 23:50:00', 20, 98);
INSERT INTO ASSIGNMENTS_PER_STUDENT VALUES (NULL, 3, 4, '2019-01-02 11:00:00', 20, 96);
INSERT INTO ASSIGNMENTS_PER_STUDENT VALUES (NULL, 9, 4, NULL , NULL, NULL);
INSERT INTO ASSIGNMENTS_PER_STUDENT VALUES (NULL, 11, 4, NULL , NULL, NULL);
INSERT INTO ASSIGNMENTS_PER_STUDENT VALUES (NULL, 6, 4, '2019-12-01 23:55:00', 20, 95);
INSERT INTO ASSIGNMENTS_PER_STUDENT VALUES (NULL, 8, 4, '2019-01-02 11:00:00', 20, 90);
INSERT INTO ASSIGNMENTS_PER_STUDENT VALUES (NULL, 14, 4, NULL , NULL, NULL);
INSERT INTO ASSIGNMENTS_PER_STUDENT VALUES (NULL, 16, 4, NULL , NULL, NULL);

INSERT INTO ASSIGNMENTS_PER_STUDENT VALUES (NULL, 6, 5, '2019-12-01 23:55:00', 20, 95);
INSERT INTO ASSIGNMENTS_PER_STUDENT VALUES (NULL, 8, 5, '2019-01-02 11:00:00', 20, 90);
INSERT INTO ASSIGNMENTS_PER_STUDENT VALUES (NULL, 14, 5, NULL , NULL, NULL);
INSERT INTO ASSIGNMENTS_PER_STUDENT VALUES (NULL, 16, 5, NULL , NULL, NULL);

INSERT INTO ASSIGNMENTS_PER_STUDENT VALUES (NULL, 1, 6, '2019-01-02 23:50:00', 20, 98);
INSERT INTO ASSIGNMENTS_PER_STUDENT VALUES (NULL, 3, 6, '2019-01-02 11:00:00', 20, 96);
INSERT INTO ASSIGNMENTS_PER_STUDENT VALUES (NULL, 9, 6, NULL , NULL, NULL);
INSERT INTO ASSIGNMENTS_PER_STUDENT VALUES (NULL, 11, 6, NULL , NULL, NULL);
INSERT INTO ASSIGNMENTS_PER_STUDENT VALUES (NULL, 5, 6, '2019-01-02 22:00:00', 20, 98);
INSERT INTO ASSIGNMENTS_PER_STUDENT VALUES (NULL, 7, 6, '2019-01-29 11:00:00', 20, 96);
INSERT INTO ASSIGNMENTS_PER_STUDENT VALUES (NULL, 13, 6, NULL , NULL, NULL);
INSERT INTO ASSIGNMENTS_PER_STUDENT VALUES (NULL, 15, 6, NULL , NULL, NULL);

INSERT INTO ASSIGNMENTS_PER_STUDENT VALUES (NULL, 6, 7, '2019-12-01 23:55:00', 20, 95);
INSERT INTO ASSIGNMENTS_PER_STUDENT VALUES (NULL, 8, 7, '2019-01-02 11:00:00', 20, 90);
INSERT INTO ASSIGNMENTS_PER_STUDENT VALUES (NULL, 14, 7, NULL , NULL, NULL);
INSERT INTO ASSIGNMENTS_PER_STUDENT VALUES (NULL, 16, 7, NULL , NULL, NULL);

INSERT INTO ASSIGNMENTS_PER_STUDENT VALUES (NULL, 2, 8, '2019-12-01 10:00:00', 20, 95);
INSERT INTO ASSIGNMENTS_PER_STUDENT VALUES (NULL, 4, 8, '2019-01-02 11:00:00',20, 100);
INSERT INTO ASSIGNMENTS_PER_STUDENT VALUES (NULL, 10, 8, NULL , NULL, NULL);
INSERT INTO ASSIGNMENTS_PER_STUDENT VALUES (NULL, 12, 8, NULL , NULL, NULL);
INSERT INTO ASSIGNMENTS_PER_STUDENT VALUES (NULL, 5, 8, '2019-01-02 22:00:00', 20, 98);
INSERT INTO ASSIGNMENTS_PER_STUDENT VALUES (NULL, 7, 8, '2019-01-29 11:00:00', 20, 96);
INSERT INTO ASSIGNMENTS_PER_STUDENT VALUES (NULL, 13, 8, NULL , NULL, NULL);
INSERT INTO ASSIGNMENTS_PER_STUDENT VALUES (NULL, 15, 8, NULL , NULL, NULL);
